/// Templates: Base strings, into which nouns can be inserted.
pub const TEMPLATES: &[&str] = &[
    "\x1F ahead",
    "Be wary of \x1F",
    "Try \x1F",
    "Need \x1F",
    "Imminent \x1F...",
    "Weakness: \x1F",
    "\x1F",
    "\x1F?",
    "Good luck",
    "I did it!",
    "Here!",
    "I can't take this...",
    "Praise the Sun!",
];

/// Fill: Nouns and concepts, for insertion into templates.
pub const FILL: &[&str] = &[
    //  Characters
    "enemy",
    "tough enemy",
    "Hollow",
    "soldier",
    "knight",
    "sniper",
    "caster",
    "giant",
    "skeleton",
    "ghost",
    "bug",
    "poison bug",
    "lizard",
    "drake",
    "flier",
    "golem",
    "statue",
    "monster",
    "strange creature",
    "demon",
    "Darkwraith",
    "dragon",
    "boss",
    "saint",
    "wretch",
    "charmer",
    "miscreant",
    "liar",
    "fatty",
    "beanpole",
    "merchant",
    "blacksmith",
    "master",
    "prisoner",
    //  Objects
    "bonfire",
    "fog wall",
    "humanity",
    "lever",
    "switch",
    "key",
    "treasure",
    "chest",
    "weapon",
    "shield",
    "projectile",
    "armour",
    "item",
    "ring",
    "sorcery scroll",
    "pyromancy scroll",
    "miracle scroll",
    "ember",
    "trap",
    "covenant",
    "amazing key",
    "amazing treasure",
    "amazing chest",
    "amazing weapon",
    "amazing shield",
    "amazing projectile",
    "amazing armour",
    "amazing item",
    "amazing ring",
    "amazing sorcery scroll",
    "amazing pyromancy scroll",
    "amazing miracle scroll",
    "amazing ember",
    "amazing trap",
    //  Techniques
    "close-ranged battle",
    "ranged battle",
    "eliminating one at a time",
    "luring it out",
    "beating to a pulp",
    "lying in ambush",
    "stealth",
    "mimicry",
    "pincer attack",
    "hitting them in one swoop",
    "fleeing",
    "charging",
    "stabbing in the back",
    "sweeping attack",
    "shield breaking",
    "head shots",
    "sorcery",
    "pyromancy",
    "miracles",
    "jumping off",
    "sliding down",
    "dashing through",
    //  Actions
    "rolling",
    "backstepping",
    "jumping",
    "attacking",
    "holding with both hands",
    "kicking",
    "a plunging attack",
    "blocking",
    "parrying",
    "locking-on",
    //  Geography
    "path",
    "hidden path",
    "shortcut",
    "detour",
    "illusory wall",
    "shortcut",
    "dead end",
    "swamp",
    "lava",
    "forest",
    "cave",
    "labyrinth",
    "safe zone",
    "danger zone",
    "sniper spot",
    "bright spot",
    "dark spot",
    "open area",
    "tight spot",
    "hiding place",
    "exchange",
    "gorgeous view",
    "fall",
    //  Orientation
    "Front",
    "Back",
    "Left",
    "Right",
    "Up",
    "Down",
    "feet",
    "head",
    "back",
    //  Body parts
    "head",
    "neck",
    "stomach",
    "back",
    "arm",
    "leg",
    "heel",
    "rear",
    "tail",
    "wings",
    "anywhere",
    //  Attribute
    "strike",
    "thrust",
    "slash",
    "magic",
    "fire",
    "lightning",
    "critical hits",
    "bleeding",
    "poison",
    "strong poison",
    "curses",
    "divine",
    "occult",
    "crystal",
    //  Concepts
    "chance",
    "hint",
    "secret",
    "happiness",
    "sorrow",
    "life",
    "death",
    "undead",
    "elation",
    "grief",
    "hope",
    "despair",
    "Light",
    "Dark",
    "bravery",
    "resignation",
    "comfort",
    "tears",
];
